#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Sat Jul 26 22:11:09 2025

set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module mask_top
